### PR TITLE
Revert "Rename workflows and branches to main"

### PR DESCRIPTION
**Pull request by sethvargo**
Reverts google-github-actions/setup-gcloud#449

### CODE REVIEW

**Review by bharathkkb — APPROVED** [review]

**Comment by TijanaJakovljevic** [comment]
👀

**Comment by JovanCucic19** [comment]
Good job @sethvargo !

**Comment by saranshkataria** [comment]
Will the branch be changed in the near future? The change broke our builds and we changed the action but it now seems to be reverted. Some insights into the decision would be helpful

**Comment by sethvargo** [comment]
We renamed the branch to `main`, but despite [GitHub's blog post](https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/), this broke existing workflows. We re-renamed the branch back to `master` and workflows should work again now. Sorry about that.

We plan to rename the branch to `main` in 2022. This will be reflected in the README after https://github.com/google-github-actions/setup-gcloud/pull/454 is merged. We do not recommend pinning to `@master` (or `@main` in the future) unless you really really really want the bleeding edge (and the risks that come with it). Instead, you should pin to `@v0` or ` specific git tag.

**Comment by 3tractorrides** [comment]
thank you for the quick action on this one!

**Comment by saranshkataria** [comment]
> We renamed the branch to `main`, but despite [GitHub's blog post](https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/), this broke existing workflows. We re-renamed the branch back to `master` and workflows should work again now. Sorry about that.
> 
> We plan to rename the branch to `main` in 2022. This will be reflected in the README after #454 is merged. We do not recommend pinning to `@master` (or `@main` in the future) unless you really really really want the bleeding edge (and the risks that come with it). Instead, you should pin to `@v0` or ` specific git tag.

Thanks. The readme mentions pinning to @master which is why we had been using that. Will look at pinning on versions and I am guessing the README also needs to be updated then?

**Comment by sethvargo** [comment]
@saranshkataria the README doesn't recommend pinning to `master`.

**Comment by saranshkataria** [comment]
> @saranshkataria the README doesn't recommend pinning to `master`.

I got confused a little but see that you have pushed changes to clarify it further. Thanks!

**Pull request merged**
