### PR TITLE
Cloud SDK snippet.yml

### PR DESCRIPTION
**Pull request by srikanth772**
Set up gcloud Cloud SDK environment

### CODE REVIEW

**Review by srikanth772 — COMMENTED** [review]
approval is done

**Comment by srikanth772** [comment]
done

**Comment by averikitsch** [comment]
Hi @srikanth772 , thank you for the PR. What is the purpose of this snippet.yaml file?

**Comment by bharathkkb** [comment]
Assuming PR made in error. Please reopen if not.

**Pull request closed without merging**
